name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          cd translate-app
          npm ci
          npm run build

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.2.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: ${{ secrets.TARGET_DIR }}
          script: |
            # Restart the Nuxt app after deployment
            cd translate-app
            npm start